[build]
# target = "riscv32imac-unknown-none-elf"
# with fp
target = "riscv32imafc-unknown-none-elf"

[alias]
r = "run --release --example"

[target.riscv32imafc-unknown-none-elf]
# runner = 'riscv64-unknown-elf-gdb -x openocd.gdb'
runner = "probe-rs run --chip HPM5361 --protocol jtag --chip-description-path ./HPMicro.yaml"

rustflags = [
    "-C",
    "link-arg=-Tmemory.x",
    "-C",
    "link-arg=-Tdevice.x",
    "-C",
    "link-arg=-Tlink.x",
    "-C",
    "link-arg=-Tdefmt.x",
    "-C",
    "link-arg=-nmagic",

    # "--emit", "obj",
    # "--emit", "asm",
]

[unstable]
build-std = ["core"]

[env]
DEFMT_LOG = "info"
